Controllers/AutenticacaoController.cs
using AutenticacaoMVC.Iservices;
using AutenticacaoMVC.Models;
using AutenticacaoMVC.Models.ViewModels;
using AutenticacaoMVC.Services;
using System;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace AutenticacaoMVC.Controllers
{
    public class AutenticacaoController : Controller
    {
        IUsuarioService _usuarioService;
        IAutenticacaoService _autenticacaoService;
        public AutenticacaoController(IUsuarioService usuarioService, IAutenticacaoService autenticacaoService)
        {
            _usuarioService = usuarioService;
            _autenticacaoService = autenticacaoService;
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(CadastroUsuarioViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }
            else
            {
                Usuario usuario = new Usuario
                {
                    Nome = viewModel.Nome,
                    Login = viewModel.Login,
                    Senha = HashService.GerarHash(viewModel.Senha)
                };

                if (_usuarioService.LoginExists(usuario))
                {
                    ModelState.AddModelError("Login", "Esse login já está em uso.");
                    return View(viewModel);
                }

                if (_usuarioService.Add(usuario))
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(viewModel);
        }
        [HttpGet]
        public ActionResult Login(string ReturnUrl)
        {
            var viewModel = new LoginViewModel
            {
                UrlRetorno = ReturnUrl
            };
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel user)
        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }
            var usuario = _usuarioService.Login(user);
            if (usuario != null)
            {
                var identity =  _autenticacaoService.CreateCooKie(usuario);
                Request.GetOwinContext().Authentication.SignIn(identity);
                if (!String.IsNullOrWhiteSpace(user.UrlRetorno) || Url.IsLocalUrl(user.UrlRetorno))
                {
                    return Redirect(user.UrlRetorno);
                }
                else
                {
                    return RedirectToAction("GetAll", "ListarUsuarios");
                }
            }
            ModelState.AddModelError("Login", "Login ou senha inválidos");
            return View(user);
        }

        public ActionResult Logout()
        {
            Request.GetOwinContext().Authentication.SignOut("AplicationCookie");

            return RedirectToAction("Index", "Home");
        }
    }
}

Controllers/PerfilController.cs
using AutenticacaoMVC.Iservices;
using AutenticacaoMVC.Models.ViewModels;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;

namespace AutenticacaoMVC.Controllers
{
    public class PerfilController : Controller
    {
        IUsuarioService _usuarioService;
        public PerfilController(IUsuarioService usuarioService)
        {
            _usuarioService = usuarioService;
        }

        [Authorize]
        public ActionResult AlterarSenha()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        public ActionResult AlterarSenha(AlterarSenhaViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var identity = User.Identity as ClaimsIdentity;
            var login = identity.Claims.FirstOrDefault(c => c.Type == "Login").Value;
            LoginViewModel loginViewModel = new LoginViewModel
            {
                Login = login,
                Senha = viewModel.SenhaAtual
            };
            var usuario = _usuarioService.Login(loginViewModel);
            if (usuario == null)
            {
                ModelState.AddModelError("SenhaAtual", "Senha incorreta");
                return View();
            }
            usuario.Senha = viewModel.NovaSenha;
            _usuarioService.AlterarSenha(usuario);

            return RedirectToAction("Index", "ListarUsuarios");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse  navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a>@User.Identity.Name</a></li>
                        <li>@Html.ActionLink("Sair", "Logout", "Autenticacao")</li>
                        <li>@Html.ActionLink("Alterar senha", "AlterarSenha", "Perfil")</li>


                    }
                    else
                    {
                        <li>@Html.ActionLink("Cadastre-se", "Cadastrar", "Autenticacao")</li>
                        <li>@Html.ActionLink("Login", "Login", "Autenticacao")</li>
                    }

                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>